### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### ISSUE THREAD

**Issue by dirknbr** [ronikobrosly/causal-curve#45]
when I run 

`gps_point = gps.point_estimate(np.array([1]))`

I get this error

```
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```

the model was trained with continours treatment in pandas format

**Comment by ronikobrosly** [comment]
Hi @dirknbr , can you include data and code to replicate this? The data can be mock/random data if that helps

**Comment by dirknbr** [comment]
sure

```
n = 200
df = pd.DataFrame()
df['X'] = np.random.normal(10, 1, n)
df['Tr'] = 10 + df.X + np.random.normal(0, 1, n)
df['Y'] = 10 + df.X + df.Tr + np.random.normal(0, 1, n)
gps = GPS_Regressor(treatment_grid_num = 20, random_seed = 512)
gps.fit(T = df['Tr'], X = df['X'], y = df['Y'])
gps_point = gps.point_estimate(np.array([1]))
```

**Comment by ronikobrosly** [comment]
Ok thanks @dirknbr , I'll take a look soon and get back to you 👍

**Comment by ronikobrosly** [comment]
Well @dirknbr , in short, numpy introduced [a breaking change in some recent version](https://github.com/numpy/numpy/issues/23231). I can confirm that 3 unit tests in this package are now broken with the most recent version of numpy. Thanks for catching this! 

Two options. The quicker one: I recommend you create a new virtual environment for your project work and force install a version of numpy < 1.20. This will have a cascading effect on the other dependencies and they'll end up being older versions too. The slightly more challenging one: could I get your help in patching `causal-curve` to work with the latest version of numpy?

**Comment by dirknbr** [comment]
ok will have a look whether I can fix it

**Comment by dirknbr** [comment]
fixed it locally and will now try to upload it, pytest passes

**Comment by abhijeetdhakane** [comment]
Will this fix be available in the latest Numpy version (stable)? I am also encountering the same problem.

**Comment by caphychan** [comment]
Hello, that patched version seems not completely solve this issue. When I run 

`gps.point_estimate(np.array([3000]))`

I still get the error :


```
ValueError                                Traceback (most recent call last)
Cell In[89], line 1
----> 1 gps.point_estimate(np.array([3000]))

File ~/.local/lib/python3.8/site-packages/causal_curve/gps_regressor.py:113, in GPS_Regressor.point_estimate(self, T)
    110 if self.outcome_type != "continuous":
    111     raise TypeError("Your outcome must be continuous to use this function!")
--> 113 return np.apply_along_axis(self._create_point_estimate, 0, T.reshape(1, -1))

File <__array_function__ internals>:200, in apply_along_axis(*args, **kwargs)

File ~/.local/lib/python3.8/site-packages/numpy/lib/shape_base.py:379, in apply_along_axis(func1d, axis, arr, *args, **kwargs)
    375 except StopIteration as e:
    376     raise ValueError(
    377         'Cannot apply_along_axis when any iteration dimensions are 0'
    378     ) from None
--> 379 res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
    381 # build a buffer for storing evaluations of func1d.
    382 # remove the requested axis, and add the new ones on the end.
    383 # laid out so that each write is contiguous.
    384 # for a tuple index inds, buff[inds] = func1d(inarr_view[inds])
    385 buff = zeros(inarr_view.shape[:-1] + res.shape, res.dtype)

File ~/.local/lib/python3.8/site-packages/causal_curve/gps_regressor.py:120, in GPS_Regressor._create_point_estimate(self, T)
    115 def _create_point_estimate(self, T):
    116     """Takes a single treatment value and produces a single point estimate
    117     in the case of a continuous outcome.
    118     """
    119     return self.gam_results.predict(
--> 120         np.array([T, self.gps_function(T).mean()]).reshape(1, -1)
    121     )

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```

**Comment by ronikobrosly** [comment]
Thanks for the heads up @abhijeetdhakane and @caphychan , I'm about to go on a short vacation but will look at this once I'm back. I suspect this will only involve a few quick changes to how the numpy arrays are handled.
